config/routes.rb
Rails.application.routes.draw do
  resources :staffs do
    collection {post :import}
  end
  get 'adminimanages/in'
  get 'adminimanages/ticket_qr'
  get 'adminimanages/index'
  get 'adminimanages/auto'
  get 'adminimanages/success_in'
  get 'adminimanages/success_out'
  get 'adminimanages/form'
  post 'adminimanages/form' => 'adminimanages#create'
  get 'adminimanages/out'
  post 'adminimanages/success'
  get 'adminimanages/error'
  get 'tyusen/hinamatsuri' => 'tyusens#hinamatsuri'
  get 'tyusen/valentine' => 'tyusens#valentine'
  post 'tyusens/lottery'
  resources :supports
  resources :stamps
  get 'site_infos' => 'site_infos#index'
  get 'users/index'
  get 'users/show'
  resources :prizes
  root 'homes#index'
  devise_for :users, :controllers => {
    :registrations => 'devise_users/registrations'
   }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  get 'homes/index'

  get 'setting' => 'homes#setting'

  get 'info' => 'homes#info'

  get 'mmmf_terms' => "helps#mmmf_terms"
  
  get 'contact' => "helps#contact"
  get 'helps/announce' => "helps#announce"
  get "helps/support"

  get 'get/stamp/:id' => 'get#stamp'
  get 'get/logs'

  get '*path', controller: 'application', action: 'render_404'
  post '*not_found', controller: 'application', action: 'routing_error'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adminimanage.rb
class Adminimanage < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv' # 追記
end

app/models/get_stamp.rb
class GetStamp < ApplicationRecord
end

app/models/prize.rb
class Prize < ApplicationRecord
    mount_uploader :image, PrizeUploader
end

app/models/site_info.rb
class SiteInfo < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
    #importメソッド
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        staff = find_by(id: row["id"]) || new
        # CSVからデータを取得し、設定する
        staff.attributes = row.to_hash.slice(*updatable_attributes)
        staff.save
        end
    end
    
    # 更新を許可するカラムを定義
    def self.updatable_attributes
        ["staff_id", "group", "info"]
    end
end

app/models/stamp.rb
class Stamp < ApplicationRecord
    mount_uploader :image, StampUploader
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/tyusen.rb
class Tyusen < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :Trackable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable,
         :lockable
end

app/controllers/get_controller.rb
class GetController < ApplicationController
  before_action -> {access_control(5)}, except: [:stamp]
  def stamp
    @get_stamp = params[:id]
    @stamp = Stamp.find_by(stamp_id: @get_stamp)
    if @stamp.nil?
      render 'errors/404', status: :not_found and return
    elsif GetStamp.find_by(student_no: current_user.student_no, stamp_id: @get_stamp) != nil
      redirect_to :root, notice: "このスタンプは獲得済みです！" and return
    end

    GetStamp.create({student_no: current_user.student_no, number: @stamp.number, stamp_id: @stamp.stamp_id})
    redirect_to :root, notice: "スタンプGET！"
  end

  def logs
    @get_logs = GetStamp.all.order(created_at: "DESC")
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: "Staff was successfully updated." }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: "Staff was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def import
    Staff.import(params[:file])
    redirect_to staffs_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.require(:staff).permit(:staff_id, :group, :info)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_cnt
        return GetStamp.where(student_no: current_user.student_no).count
    end
end

app/helpers/get_helper.rb
module GetHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
    require 'chunky_png'
    
    def stamp_list(index)
        stamp_list = ["creators", "design", "it", "tech"]
        path = "/images/stamps/#{stamp_list[index-1]}.png"
        @get_stamp.each do |get_stamp|
            if get_stamp.number == index
                begin
                    path = @stamp.find_by(number: index).image.url
                rescue
                    path = "/images/noimage.png"
                end
            end
        end
        path
    end

    def qrcode_tag(url, _options = {})
        qr = ::RQRCode::QRCode.new(url)
        ChunkyPNG::Image.from_datastream(qr.as_png.resize(200,200).to_datastream).to_data_url
    end

    # ざわつかせる
    def zawa 
        if rand(1..10) >= 8
            true
        else  
            false        
        end
    end
end

app/helpers/prizes_helper.rb
module PrizesHelper
    
    def check_image(image)
        if image.nil?
            "/images/noimage.png"
        else
            image
        end
    end

end

app/helpers/site_infos_helper.rb
module SiteInfosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
    require 'chunky_png'

    def qrcode_tag(url, _options = {})
        qr = ::RQRCode::QRCode.new(url)
        ChunkyPNG::Image.from_datastream(qr.as_png.to_datastream).to_data_url
    end

    def stamp_number(number)
        case number
        when 1 then
            "クリエイター"
        when 2 then
            "デザイン"
        when 3 then
            "IT"
        when 4 then   
            "テクノロジー"
        end
    end
end

app/helpers/supports_helper.rb
module SupportsHelper
    def tabfour(i)
        return "tabfour#{i}"
    end
end

app/helpers/tyusens_helper.rb
module TyusensHelper

    def check_image(image)
        if image.nil?
            "/images/noimage.png"
        else
            image
        end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :staff_id %>
    <%= form.text_field :staff_id %>
  </div>

  <div class="field">
    <%= form.label :group %>
    <%= form.text_field :group %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1><%= link_to 'New Staff', new_staff_path %>

<table>
  <thead>
    <tr>
      <th>Staff</th>
      <th>Group</th>
      <th>Info</th>
      <th>QR</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
    <% @qr = ::RQRCode::QRCode.new(staff.staff_id,  level: :h) %>
      <tr>
        <td><%= staff.staff_id %></td>
        <td><%= staff.group %></td>
        <td><%= staff.info %></td>
        <td><%= image_tag ChunkyPNG::Image.from_datastream(@qr.as_png.to_datastream).resize(170, 170).to_data_url %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>
<%= form_tag import_staffs_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>
<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff:</strong>
  <%= @staff.staff_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @staff.group %>
</p>

<p>
  <strong>Info:</strong>
  <%= @staff.info %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>