config/routes.rb
Rails.application.routes.draw do
  resources :staffs do
    collection {post :import}
  end
  get 'adminimanages/in'
  get 'adminimanages/ticket_qr'
  get 'adminimanages/index'
  get 'adminimanages/auto'
  get 'adminimanages/success_in'
  get 'adminimanages/success_out'
  get 'adminimanages/form'
  post 'adminimanages/form' => 'adminimanages#create'
  get 'adminimanages/out'
  post 'adminimanages/success'
  get 'adminimanages/error'
  get 'tyusen/hinamatsuri' => 'tyusens#hinamatsuri'
  get 'tyusen/valentine' => 'tyusens#valentine'
  post 'tyusens/lottery'
  resources :supports
  resources :stamps
  get 'site_infos' => 'site_infos#index'
  get 'users/index'
  get 'users/show'
  resources :prizes
  root 'homes#index'
  devise_for :users, :controllers => {
    :registrations => 'devise_users/registrations'
   }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  get 'homes/index'

  get 'setting' => 'homes#setting'

  get 'info' => 'homes#info'

  get 'mmmf_terms' => "helps#mmmf_terms"
  
  get 'contact' => "helps#contact"
  get 'helps/announce' => "helps#announce"
  get "helps/support"

  get 'get/stamp/:id' => 'get#stamp'
  get 'get/logs'

  get '*path', controller: 'application', action: 'render_404'
  post '*not_found', controller: 'application', action: 'routing_error'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adminimanage.rb
class Adminimanage < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv' # 追記
end

app/models/get_stamp.rb
class GetStamp < ApplicationRecord
end

app/models/prize.rb
class Prize < ApplicationRecord
    mount_uploader :image, PrizeUploader
end

app/models/site_info.rb
class SiteInfo < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
    #importメソッド
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        staff = find_by(id: row["id"]) || new
        # CSVからデータを取得し、設定する
        staff.attributes = row.to_hash.slice(*updatable_attributes)
        staff.save
        end
    end
    
    # 更新を許可するカラムを定義
    def self.updatable_attributes
        ["staff_id", "group", "info"]
    end
end

app/models/stamp.rb
class Stamp < ApplicationRecord
    mount_uploader :image, StampUploader
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/tyusen.rb
class Tyusen < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :Trackable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable,
         :lockable
end

app/controllers/get_controller.rb
class GetController < ApplicationController
  before_action -> {access_control(5)}, except: [:stamp]
  def stamp
    @get_stamp = params[:id]
    @stamp = Stamp.find_by(stamp_id: @get_stamp)
    if @stamp.nil?
      render 'errors/404', status: :not_found and return
    elsif GetStamp.find_by(student_no: current_user.student_no, stamp_id: @get_stamp) != nil
      redirect_to :root, notice: "このスタンプは獲得済みです！" and return
    end

    GetStamp.create({student_no: current_user.student_no, number: @stamp.number, stamp_id: @stamp.stamp_id})
    redirect_to :root, notice: "スタンプGET！"
  end

  def logs
    @get_logs = GetStamp.all.order(created_at: "DESC")
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :set_support, only: %i[ show edit update destroy ]
  before_action -> {access_control(2)}

  # GET /supports or /supports.json
  def index
    @supports = Support.all.order(:kind, :order)
  end

  # GET /supports/1 or /supports/1.json
  def show
  end

  # GET /supports/new
  def new
    @support = Support.new
  end

  # GET /supports/1/edit
  def edit
  end

  # POST /supports or /supports.json
  def create
    @support = Support.new(support_params)

    respond_to do |format|
      if @support.save
        format.html { redirect_to @support, notice: "Support was successfully created." }
        format.json { render :show, status: :created, location: @support }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supports/1 or /supports/1.json
  def update
    respond_to do |format|
      if @support.update(support_params)
        format.html { redirect_to @support, notice: "Support was successfully updated." }
        format.json { render :show, status: :ok, location: @support }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @support.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supports/1 or /supports/1.json
  def destroy
    @support.destroy
    respond_to do |format|
      format.html { redirect_to supports_url, notice: "Support was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support
      @support = Support.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def support_params
      params.require(:support).permit(:question, :answer, :kind, :order)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_cnt
        return GetStamp.where(student_no: current_user.student_no).count
    end
end

app/helpers/get_helper.rb
module GetHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
    require 'chunky_png'
    
    def stamp_list(index)
        stamp_list = ["creators", "design", "it", "tech"]
        path = "/images/stamps/#{stamp_list[index-1]}.png"
        @get_stamp.each do |get_stamp|
            if get_stamp.number == index
                begin
                    path = @stamp.find_by(number: index).image.url
                rescue
                    path = "/images/noimage.png"
                end
            end
        end
        path
    end

    def qrcode_tag(url, _options = {})
        qr = ::RQRCode::QRCode.new(url)
        ChunkyPNG::Image.from_datastream(qr.as_png.resize(200,200).to_datastream).to_data_url
    end

    # ざわつかせる
    def zawa 
        if rand(1..10) >= 8
            true
        else  
            false        
        end
    end
end

app/helpers/prizes_helper.rb
module PrizesHelper
    
    def check_image(image)
        if image.nil?
            "/images/noimage.png"
        else
            image
        end
    end

end

app/helpers/site_infos_helper.rb
module SiteInfosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
    require 'chunky_png'

    def qrcode_tag(url, _options = {})
        qr = ::RQRCode::QRCode.new(url)
        ChunkyPNG::Image.from_datastream(qr.as_png.to_datastream).to_data_url
    end

    def stamp_number(number)
        case number
        when 1 then
            "クリエイター"
        when 2 then
            "デザイン"
        when 3 then
            "IT"
        when 4 then   
            "テクノロジー"
        end
    end
end

app/helpers/supports_helper.rb
module SupportsHelper
    def tabfour(i)
        return "tabfour#{i}"
    end
end

app/helpers/tyusens_helper.rb
module TyusensHelper

    def check_image(image)
        if image.nil?
            "/images/noimage.png"
        else
            image
        end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/supports/_form.html.erb
<%= form_with(model: support) do |form| %>
  <% if support.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(support.errors.count, "error") %> 保存できませんでした:</h2>

      <ul>
        <% support.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="scaf_table">
  <tr>
    <th>質問</th><td><%= form.text_field :question, class: "form-control", required: true, autofocus: true %></td>
  </tr>
  <tr>
    <th>回答</th><td><%= form.text_field :answer, class: "form-control", required: true %></td>
  </tr>
  <tr>
    <th>種類</th><td><%= form.text_field :kind, class: "form-control", required: true %></td>
  </tr>
  <tr>
    <th>表示順序</th><td><%= form.number_field :order, class: "form-control", required: true %></td>
  </tr>
</table>
  <div style="text-align:center;">
    <%= form.submit %>
  </div>
<% end %>

app/views/supports/edit.html.erb
<h3 class="scaf_section">Q&Aの編集</h3>

<%= render 'form', support: @support %>

<div class="scaf_button" >
<%= link_to '戻る', supports_path %>
</div>

app/views/supports/index.html.erb
<div class="scaf_table">
<h3 class="scaf_section">スタンプ一覧</h3>
<div class="scaf_button">
  <%= link_to '新規登録', new_support_path %>
</div>
<table>
  <thead>
    <tr>
      <th>質問</th>
      <th>回答</th>
      <th>種類</th>
      <th>表示順序</th>
    </tr>
  </thead>

  <tbody>
    <% @supports.each do |support| %>
      <tr>
        <td><%= link_to support.question, support %></td>
        <td><%= support.answer %></td>
        <td><%= support.kind %></td>
        <td><%= support.order %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/supports/new.html.erb
<h3 class="scaf_section">新規登録</h3>

<%= render 'form', support: @support %>

<div class="scaf_button" >
<%= link_to '戻る', supports_path %>
</div>

app/views/supports/show.html.erb
<div class="scaf_table">
<h3 class="scaf_section">Q&Aの詳細</h3>
<div class="scaf_button" >
  <%= link_to '編集', edit_support_path(@support) %>  |  <%= link_to '一覧に戻る', supports_path %></td>
</div>
<table>
  <tr>
    <th>質問</th><td><%= @support.question %></td>
  </tr>
  <tr>
    <th>回答</th><td><%= @support.answer %></td>
  </tr>
  <tr>
    <th>種類</th><td><%= @support.kind %></td>
  </tr>
  <tr>
    <th>表示順序</th><td><%= @support.order %></td>
  </tr>
</table>
</div>
<div class="scaf_button" >
  <td><%= link_to '削除', @support, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
</div>