config/routes.rb
Rails.application.routes.draw do
  resources :staffs do
    collection {post :import}
  end
  get 'adminimanages/in'
  get 'adminimanages/ticket_qr'
  get 'adminimanages/index'
  get 'adminimanages/auto'
  get 'adminimanages/success_in'
  get 'adminimanages/success_out'
  get 'adminimanages/form'
  post 'adminimanages/form' => 'adminimanages#create'
  get 'adminimanages/out'
  post 'adminimanages/success'
  get 'adminimanages/error'
  get 'tyusen/hinamatsuri' => 'tyusens#hinamatsuri'
  get 'tyusen/valentine' => 'tyusens#valentine'
  post 'tyusens/lottery'
  resources :supports
  resources :stamps
  get 'site_infos' => 'site_infos#index'
  get 'users/index'
  get 'users/show'
  resources :prizes
  root 'homes#index'
  devise_for :users, :controllers => {
    :registrations => 'devise_users/registrations'
   }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  get 'homes/index'

  get 'setting' => 'homes#setting'

  get 'info' => 'homes#info'

  get 'mmmf_terms' => "helps#mmmf_terms"
  
  get 'contact' => "helps#contact"
  get 'helps/announce' => "helps#announce"
  get "helps/support"

  get 'get/stamp/:id' => 'get#stamp'
  get 'get/logs'

  get '*path', controller: 'application', action: 'render_404'
  post '*not_found', controller: 'application', action: 'routing_error'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adminimanage.rb
class Adminimanage < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv' # 追記
end

app/models/get_stamp.rb
class GetStamp < ApplicationRecord
end

app/models/prize.rb
class Prize < ApplicationRecord
    mount_uploader :image, PrizeUploader
end

app/models/site_info.rb
class SiteInfo < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
    #importメソッド
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        staff = find_by(id: row["id"]) || new
        # CSVからデータを取得し、設定する
        staff.attributes = row.to_hash.slice(*updatable_attributes)
        staff.save
        end
    end
    
    # 更新を許可するカラムを定義
    def self.updatable_attributes
        ["staff_id", "group", "info"]
    end
end

app/models/stamp.rb
class Stamp < ApplicationRecord
    mount_uploader :image, StampUploader
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/tyusen.rb
class Tyusen < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :Trackable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable,
         :lockable
end

app/helpers/get_helper.rb
module GetHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
    require 'chunky_png'
    
    def stamp_list(index)
        stamp_list = ["creators", "design", "it", "tech"]
        path = "/images/stamps/#{stamp_list[index-1]}.png"
        @get_stamp.each do |get_stamp|
            if get_stamp.number == index
                begin
                    path = @stamp.find_by(number: index).image.url
                rescue
                    path = "/images/noimage.png"
                end
            end
        end
        path
    end

    def qrcode_tag(url, _options = {})
        qr = ::RQRCode::QRCode.new(url)
        ChunkyPNG::Image.from_datastream(qr.as_png.resize(200,200).to_datastream).to_data_url
    end

    # ざわつかせる
    def zawa 
        if rand(1..10) >= 8
            true
        else  
            false        
        end
    end
end

app/helpers/prizes_helper.rb
module PrizesHelper
    
    def check_image(image)
        if image.nil?
            "/images/noimage.png"
        else
            image
        end
    end

end

app/helpers/site_infos_helper.rb
module SiteInfosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
    require 'chunky_png'

    def qrcode_tag(url, _options = {})
        qr = ::RQRCode::QRCode.new(url)
        ChunkyPNG::Image.from_datastream(qr.as_png.to_datastream).to_data_url
    end

    def stamp_number(number)
        case number
        when 1 then
            "クリエイター"
        when 2 then
            "デザイン"
        when 3 then
            "IT"
        when 4 then   
            "テクノロジー"
        end
    end
end

app/helpers/supports_helper.rb
module SupportsHelper
    def tabfour(i)
        return "tabfour#{i}"
    end
end

app/helpers/tyusens_helper.rb
module TyusensHelper

    def check_image(image)
        if image.nil?
            "/images/noimage.png"
        else
            image
        end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <% next if msg_type == 'timedout' %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href=<%= request.path %> class="close" data-dismiss="alert">×</a>
    <%= sanitize msg, tags: %w(br) %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
    <ul>
        <li><a href="/contact">お問い合わせ先</a></li>
        <li><a href="/mmmf_terms">利用規約</a></li>
    </ul>
    <p class="footer-p"><span class="footer-span">produced by 学生委員会"Act"</span></p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
    <div class="headerNavOuter">
        <h1 class="siteIcon">
          <%= link_to image_tag('/images/mmmf.png',  class: 'navbar-brand'), root_path %>
        </h1>
    
        <nav class="headerNav">
          <% if user_signed_in? %>
            <ul class="navList">
              <% if User.find(current_user.id).role_flag.to_i >= 2 %>
                <li class="navItem">
                  <%= link_to '管理画面', setting_path, class: 'nav-link' %>
                </li>
              <% end %>
              <li class="navItem">
                  <%= link_to '企画詳細', "https://act-neec.org/wakatsuku2022", target: "_brank", rel: "noopener noreferrer", class: 'nav-link' %>
              </li>
              <li class="navItem">
                  <%= link_to 'Q&A', helps_support_path, class: 'nav-link' %>
              </li>
            </ul>
            <ul class="navList">
              <li class="navItem-logout">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            </ul>
          <% else %>
            <ul class="navList">
              <li class="navItem">
                  <%= link_to '企画詳細', "https://act-neec.org/wakatsuku2022", target: "_brank", rel: "noopener noreferrer", class: 'nav-link' %>
              </li>
              <li class="navItem">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
              </li>
              <li class="navItem">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="navItem">
                  <%= link_to 'Q&A', helps_support_path, class: 'nav-link' %>
              </li>
            </ul>
          <% end %>
        </nav>
    
        <div class="hamburger_btn" id="js-hamburger">
            <span class="hamburger_line hamburger_line_1"></span>
            <span class="hamburger_line hamburger_line_2"></span>
            <span class="hamburger_line hamburger_line_3"></span>
        </div>

        <div class="black-bg" id="js-black-bg"></div>
    </div>
</header>
<div class="sectionWrapper"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>イベント支援サービス | Stamp MMMF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <% unless current_page?(adminimanages_ticket_qr_path) %>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>
    <% end %>
    <%= yield %>
    <% unless current_page?(adminimanages_ticket_qr_path) %>
    <div class="push"></div>
    <%= render 'layouts/footer' %>
    <% end %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>